config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  root to: "users#notifications"

  resources :users, only:[:show, :edit, :update] do
    collection do
      get 'other'
      get 'projects'
      get 'notifications'
    end
  end

  resources :projects do
    collection do
      get 'other'
    end
  end

  resources :followers, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :profile
  has_many :projects

  has_many :following_users, class_name: 'Follower', foreign_key: 'followed_id'
  has_many :followers, through: :following_users

  has_many :followed_users, class_name: 'Follower', foreign_key: 'user_id'
  has_many :followings, through: :followed_users

  has_many :likes, class_name: 'Like', foreign_key: 'user_id'
  has_many :liked_projects, through: :likes, source: :project

  has_many :activities

  accepts_nested_attributes_for :profile, allow_destroy: true

  def name
    profile ? profile.name : email
  end

  def following?(user_id)
    followings.where(id: user_id).present?
  end

  def my_like?(like_id)
    likes.find{ |like| like.id == like_id }.present?
  end

  def liked_project?(project_id)
    liked_projects.where(id: project_id).present?
  end

  def my_project?(project_id)
    projects.find{ |project| project.id == project_id }.present?
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def projects
    @projects = Project.for_user(current_user.id)
    @projects = @projects.page(params[:page]).per_page(PAGE_SIZE)
  end

  def other
    @users = User.where.not(id: current_user.id)
    @users = @users.page(params[:page]).per_page(PAGE_SIZE)
  end

  def notifications
    @activities = Activity.for_user(current_user.followings.map(&:id))
                    .order('created_at desc')
    @activities = @activities.page(params[:page]).per_page(PAGE_SIZE)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update_attributes(users_params)

    if @user.valid?
      flash[:success] = 'The profile data was updated successfully!'
      redirect_to root_path
    else
      flash[:error] = join_errors(@user)
      render 'edit'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def users_params
    params.require(:user).permit(:password, profile_attributes: [:id, :name, :gender, :age, :country])
  end
end

app/views/users/edit.html.erb
<%= render partial: 'shared/page_header', locals:{ header_name: 'User profile' } %>
<%= form_tag(user_path(@user), method: :put, class: 'form-horizontal') do %>
  <%= hidden_field_tag 'user[profile_attributes][id]', @user.profile.try(:id), id: "user_profile_id" %>
  <div class="form-group">
    <%= label_tag :user_name, 'Name', class: "col-lg-3 control-label" %>
    <div class="col-lg-8">
      <div class="bs-component">
        <%= text_field_tag 'user[profile_attributes][name]', @user.profile.try(:name), class: "form-control", prompt: 'Please enter a name', id: 'user_name' %>
      </div>
    </div>
  </div>
  <div class="form-group">
    <%= label_tag :user_gender, 'Gender', class: "col-lg-3 control-label" %>
    <div class="col-lg-8">
      <div class="bs-component">
        <%= select_tag 'user[profile_attributes][gender]', options_for_select(Profile::GENDER_LIST.map{ |k,v| [v,k] }, @user.profile.try(:gender)), class: "form-control", placeholder: 'Please select gender', id: 'user_gender' %>
      </div>
    </div>
  </div>
  <div class="form-group">
    <%= label_tag :user_age, 'Age', class: "col-lg-3 control-label" %>
    <div class="col-lg-8">
      <div class="bs-component">
        <%= text_field_tag 'user[profile_attributes][age]', @user.profile.try(:age), class: "form-control", prompt: 'Please enter the age', id: 'user_age' %>
      </div>
    </div>
  </div>
   <div class="form-group">
    <%= label_tag :user_country, 'Country', class: "col-lg-3 control-label" %>
    <div class="col-lg-8">
      <div class="bs-component">
        <%= select_tag 'user[profile_attributes][country]', options_for_select(ISO3166::Country.all.map{|v| [v.name, v.name] }, @user.profile.try(:country)), class: "form-control", placeholder: 'Please select a country', id: 'user_country' %>
      </div>
    </div>
  </div>
  <div class="form-group">
    <div class="col-lg-3"></div>
    <div class="col-lg-8">
      <div class="bs-component">
        <%= submit_tag 'Update', class: "btn bg-primary btn-primary" %>
      </div>
    </div>
  </div>
<% end %>

app/views/users/notifications.html.erb
<%= render partial: 'shared/page_header', locals:{ header_name: 'Friends activity' } %>
<div class="panel">
  <div class="panel-body">
    <div class="clearfix mb10"></div>
    <% if @activities.any? %>
      <table class="table batch table-hover table-responsive">
        <thead>
          <th>User name</th>
          <th>Activity</th>
          <th>Logged at</th>
        </thead>
        <tbody>
          <% @activities.each do |activity| %>
            <tr>
              <td><%= link_to(activity.user.name, user_path(activity.user.id)) %></td>
              <td><%= activity.message %></td>
              <td><%= show_date(activity.created_at) %></td>
            </tr>
          <% end %>
         </tbody>
      </table>
      <%= will_paginate @activities, renderer: BootstrapPagination::Rails %>
    <% else %>
      <div class="text-center">Your friends don't have any activity</div>
    <% end %>
  </div>
</div>

app/views/users/other.html.erb
<%= render partial: 'shared/page_header', locals:{ header_name: 'Other users' } %>
<div class="panel">
  <div class="panel-body">
    <div class="clearfix mb10"></div>
      <% if @users.any? %>
        <table class="table batch table-hover table-responsive">
          <thead>
            <th>Name</th>
            <th>Email</th>
            <th>Country</th>
            <th>Gender</th>
            <th>Age</th>
            <th>Following</th>
            <th>Followers</th>
            <th>Actions</th>
          </thead>
          <tbody>
            <% @users.each do |user| %>
              <tr>
                <td><%= user.profile.try(:name) %></td>
                <td><%= link_to(user.email, user_path(user.id)) %></td>
                <td><%= user.profile.try(:country) %></td>
                <td><%= user.profile.try(:gender) %></td>
                <td><%= user.profile.try(:age) %></td>
                <td><%= user.followings.count %></td>
                <td><%= user.followers.count %></td>
                <td><%= show_followers_link(user.id) %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <%= will_paginate @users, renderer: BootstrapPagination::Rails %>
      <% else %>
        <div class="text-center">There are no users.</div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/projects.html.erb
<%= render partial: 'shared/page_header', locals:{ header_name: 'My projects' } %>
<div class="form-group">
  <%= link_to('Create a new project', new_project_path, class: 'btn btn-primary') %>
</div>
<div class="panel">
  <div class="panel-body">
    <div class="clearfix mb10"></div>
    <% if @projects.any? %>
      <table class="table batch table-hover table-responsive">
        <thead>
          <th>Project name</th>
          <th>Likes</th>
          <th>Created at</th>
          <th>Actions</th>
        </thead>
        <tbody>
          <% @projects.each do |project| %>
            <tr>
              <td><%= link_to(project.name, edit_project_path(project.id)) %></td>
              <td><%= project.likes.count %></td>
              <td><%= show_date(project.created_at) %></td>
              <td>
                <%= link_to('Edit', edit_project_path(project.id)) %> |
                <%= show_like_link(project.id) %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= will_paginate @projects, renderer: BootstrapPagination::Rails %>
    <% else %>
      <div class="text-center">There are no projects.</div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<%= render partial: 'shared/page_header', locals:{ header_name: 'User profile details' } %>
<div class='form-horizontal'>
  <div class="form-group">
    <%= label_tag :user_email, 'Email', class: "col-lg-3 control-label" %>
    <div class="col-lg-8">
      <div class="bs-component">
        <%= text_field_tag 'user[email]', @user.email, class: "form-control", id: 'user_email', readonly: true %>
      </div>
    </div>
  </div>
  <div class="form-group">
    <%= label_tag :user_name, 'Name', class: "col-lg-3 control-label" %>
    <div class="col-lg-8">
      <div class="bs-component">
        <%= text_field_tag 'user[profile_attributes][name]', @user.profile.try(:name), class: "form-control", id: 'user_name', readonly: true %>
      </div>
    </div>
  </div>
  <div class="form-group">
    <%= label_tag :user_gender, 'Gender', class: "col-lg-3 control-label" %>
    <div class="col-lg-8">
      <div class="bs-component">
        <%= text_field_tag 'user[profile_attributes][gender]', Profile::GENDER_LIST[@user.profile.try(:gender)], class: "form-control", id: 'user_gender', readonly: true %>
      </div>
    </div>
  </div>
  <div class="form-group">
    <%= label_tag :user_age, 'Age', class: "col-lg-3 control-label" %>
    <div class="col-lg-8">
      <div class="bs-component">
        <%= text_field_tag 'user[profile_attributes][age]', @user.profile.try(:age), class: "form-control", id: 'user_age', readonly: true %>
      </div>
    </div>
  </div>
</div>