config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  root to: "users#notifications"

  resources :users, only:[:show, :edit, :update] do
    collection do
      get 'other'
      get 'projects'
      get 'notifications'
    end
  end

  resources :projects do
    collection do
      get 'other'
    end
  end

  resources :followers, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
end

app/views/shared/_header.html.erb
<%- if user_signed_in? %>
  <nav role="navigation" class="navbar navbar-default">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" data-target="#navbarCollapse" data-toggle="collapse" class="navbar-toggle">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
      </button>
    </div>
    <div id="navbarCollapse" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li>
          <%= link_to 'My projects', projects_users_path %>
        </li>
        <li>
          <%= link_to 'Other projects', other_projects_path %>
        </li>
        <li>
          <%= link_to 'Other users', other_users_path %>
        </li>
        <li>
          <%= link_to 'Friends activity', notifications_users_path %>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <%- if user_signed_in? %>
          <li>
            <p class="navbar-text">Signed in as <%= link_to(current_user.email, edit_user_path(current_user.id)) %></p>
          </li>
          <li>
            <%= link_to 'Log out', destroy_user_session_path, :method => :delete %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>
<% end %>

app/views/shared/_page_header.html.erb
<div class="page-header">
  <h3><%= header_name %></h3>
</div>