config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  root to: "users#notifications"

  resources :users, only:[:show, :edit, :update] do
    collection do
      get 'other'
      get 'projects'
      get 'notifications'
    end
  end

  resources :projects do
    collection do
      get 'other'
    end
  end

  resources :followers, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  has_many :likes

  scope :for_user, -> (user_id) { where(user_id: user_id) }
  scope :not_for_user, -> (user_id) {  where.not(user_id: user_id) }

  validates :name, :user_id, presence: true
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def other
    @projects = Project.not_for_user(current_user.id)
    @projects = @projects.page(params[:page]).per_page(PAGE_SIZE)
  end

  def new
    @project = Project.new
  end

  def create
    params[:project][:user_id] = current_user.id

    @project = Project.new(project_params)

    if @project.save
      Activity.log({
        user_id: current_user.id,
        action: 'create_project',
        message: "#{current_user.name} created the project #{@project.name}"
      })

      flash[:success] = 'The new project was saved successfully!'
      redirect_to projects_users_path
    else
      flash[:error] = join_errors(@project)
      render 'new'
    end
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    @project.update_attributes(project_params)

    if @project.valid?
      Activity.log({
        user_id: current_user.id,
        action: 'update_project',
        message: "#{current_user.name} updatec the project #{@project.name}"
      })

      flash[:success] = 'The project was updated successfully!'
      redirect_to projects_users_path
    else
      flash[:error] = join_errors(@project)
      render 'edit'
    end
  end

  def show
    @project = Project.find(params[:id])
  end

  private

  def project_params
    params.require(:project).permit(:name, :user_id)
  end
end

app/views/projects/_form.html.erb
<%= form_tag(url, method: method, class: 'form-horizontal') do %>
  <div class="form-group">
    <%= label_tag :project_name, 'Project Name', class: "col-lg-3 control-label" %>
    <div class="col-lg-8">
      <div class="bs-component">
        <%= text_field_tag 'project[name]', @project['name'], class: "form-control", prompt: 'Please enter a name' %>
      </div>
    </div>
  </div>
  <div class="form-group">
    <div class="col-lg-3"></div>
    <div class="col-lg-8">
      <div class="bs-component">
        <%= submit_tag projects_submit_button_texf(method), class: "btn bg-primary btn-primary" %>
      </div>
    </div>
  </div>
<% end %>

app/views/projects/edit.html.erb
<%= render partial: 'shared/page_header', locals: { header_name: 'Edit project' } %>
<%= render partial: 'form', locals: { url: project_path(@project.id), method: :put } %>

app/views/projects/new.html.erb
<%= render partial: 'shared/page_header', locals: { header_name: 'New project' } %>
<%= render partial: 'form', locals: { url: projects_path, method: :post } %>

app/views/projects/other.html.erb
<%= render partial: 'shared/page_header', locals:{ header_name: 'Other projects' } %>
<div class="panel">
  <div class="panel-body">
    <div class="clearfix mb10"></div>
    <% if @projects.any? %>
      <table class="table batch table-hover table-responsive">
        <thead>
          <th>Project name</th>
          <th>User name</th>
          <th>Likes</th>
          <th>Created at</th>
          <th>Actions</th>
        </thead>
        <tbody>
          <% @projects.each do |project| %>
            <tr>
              <td><%= link_to(project.name, project_path(project.id)) %></td>
              <td><%= link_to(project.user.name, user_path(project.user.id)) %></td>
              <td><%= project.likes.count %></td>
              <td><%= show_date(project.created_at) %></td>
              <td><%= show_like_link(project.id) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= will_paginate @projects, renderer: BootstrapPagination::Rails %>
    <% else %>
      <div class="text-center">There are no projects.</div>
    <% end %>
  </div>
</div>

app/views/projects/show.html.erb
<div class='form-horizontal'>
  <div class="form-group">
    <%= label_tag :project_name, 'Project Name', class: "col-lg-3 control-label" %>
    <div class="col-lg-8">
      <div class="bs-component">
        <%= text_field_tag 'project[name]', @project['name'], class: "form-control", prompt: 'Please enter a name', readonly: true %>
      </div>
    </div>
  </div>
</div>